version: '2'

services:
  # backend
  # ****************************************
  backend:
    container_name: Backend
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    environment: 
      - NODE_ENV=development
    command: npm run start:dev
    networks:
      - nestjs-react-pagination
    depends_on:
      - mongodb
  # frontend 
  # ****************************************
  frontend:
    container_name: Frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - ./usr/src/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
      - REACT_APP_NODE_ENV=development
    command: npm run start
    networks:
      - nestjs-react-pagination
    depends_on:
      - backend
  #mongodb
  # ****************************************
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart:  always
    networks:
      - nestjs-react-pagination
networks:
  nestjs-react-pagination: 


  
  
    




